version: '3.7'

services:
  learning_gitlab:
    image: geircode/learning_gitlab:latest
    build:
      context: .
      dockerfile: Dockerfile
      args:
        # This will overwrite the default build arguments in the Dockerfile with the value of the enviroment variable value
        # The value "DOCKER_LATEST_VERSION_FILE" comes from either .env or from the shell running the docker-compose command
        docker_latest_version_file_arg: ${DOCKER_LATEST_VERSION_FILE}        
    container_name: learning_gitlab-1
    volumes:
      # - ".:/app"       
      - "/var/run/docker.sock:/var/run/docker.sock"
    networks:
      - learning_gitlab_network
networks:
  learning_gitlab_network:
    name: learning_gitlab_network
    external: true
          