version: '3.7'

services:
      
  gitlab-server:
    image: 'gitlab/gitlab-ce:latest'
    restart: always
    hostname: 'gitlab-server'
    container_name: 'gitlab-server'
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'http://gitlab-server:8930'
        gitlab_rails['gitlab_shell_ssh_port'] = 2225
    ports:
      - '8930:8930'
      - '2225:22'
    networks:
      - gitlab-network

  gitlab_runner1:
    image: gitlab/gitlab-runner:latest
    container_name: gitlab_runner1
    hostname: gitlab_runner1
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock'
    networks:
      - gitlab-network

  gitlab_runner2:
    image: gitlab/gitlab-runner:latest
    container_name: gitlab_runner2
    hostname: gitlab_runner2
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock'
    networks:
      - gitlab-network

networks:
  gitlab-network:
    name: gitlab-network

